apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - port: 8000
  selector:
    app: server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        version: v1
    spec:
      containers:
      - name: server
        image: server-message-board:latest
        imagePullPolicy: Never
        env:
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: host
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: dbname
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
        ports:
        - containerPort: 8000